name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nao329-portfolio # the name of the project on Deno Deploy
          entrypoint: portfolio/index.html # the entrypoint to deploy
